services:
  postgres:
    image: postgis/postgis:15-3.3  # PostGIS on top of PostgreSQL 15
    container_name: postgres_postgis
    restart: always
    environment:
      POSTGRES_DB: uberDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_postgis_data  # Named volume for easier identification